/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TaskDSLUiModule extends AbstractTaskDSLUiModule {
  public TaskDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
