/*
 * generated by Xtext 2.32.0
 */
package persons.tasks.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TaskDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("persons/tasks/parser/antlr/internal/InternalTaskDSL.tokens");
	}
}
