/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.generator;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import persons.tasks.taskDSL.Planning;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TaskDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IteratorExtensions.<EObject>head(resource.getAllContents());
    final Planning root = ((Planning) _head);
    if ((root != null)) {
      String _lastSegment = resource.getURI().lastSegment();
      String _plus = ("generated/" + _lastSegment);
      String path = (_plus + "/");
      fsa.generateFile((path + "PlanningInfo.txt"), TextGenerator.toText(root));
      fsa.generateFile((path + "PlanningOverview.html"), HtmlGenerator.toHtml(root));
    }
  }
}
