/*
 * generated by Xtext 2.32.0
 */
package persons.tasks.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTaskDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(persons.tasks.taskDSL.TaskDSLPackage.eINSTANCE);
		return result;
	}
}
