/**
 * generated by Xtext 2.32.0
 */
package persons.tasks;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TaskDSLStandaloneSetup extends TaskDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new TaskDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
