/*
 * generated by Xtext 2.32.0
 */
package persons.tasks.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import persons.tasks.ui.internal.TasksActivator;

public class TaskDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TasksActivator.getInstance().getInjector("persons.tasks.TaskDSL");
	}

}
