/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see persons.tasks.taskDSL.TaskDSLPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
} // Action
