/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.taskDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks.taskDSL.ExpressionPlus#getSub <em>Sub</em>}</li>
 * </ul>
 *
 * @see persons.tasks.taskDSL.TaskDSLPackage#getExpressionPlus()
 * @model
 * @generated
 */
public interface ExpressionPlus extends IntExpression
{
  /**
   * Returns the value of the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub</em>' containment reference.
   * @see #setSub(IntExpression)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getExpressionPlus_Sub()
   * @model containment="true"
   * @generated
   */
  IntExpression getSub();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.ExpressionPlus#getSub <em>Sub</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub</em>' containment reference.
   * @see #getSub()
   * @generated
   */
  void setSub(IntExpression value);

} // ExpressionPlus
