/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link persons.tasks.taskDSL.Task#getName <em>Name</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getAction <em>Action</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getPersons <em>Persons</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getPrio <em>Prio</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getDuration <em>Duration</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getProjects <em>Projects</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getUse <em>Use</em>}</li>
 *   <li>{@link persons.tasks.taskDSL.Task#getExtends <em>Extends</em>}</li>
 * </ul>
 *
 * @see persons.tasks.taskDSL.TaskDSLPackage#getTask()
 * @model
 * @generated
 */
public interface Task extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.Task#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.Task#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' reference list.
   * The list contents are of type {@link persons.tasks.taskDSL.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' reference list.
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Persons()
   * @model
   * @generated
   */
  EList<Person> getPersons();

  /**
   * Returns the value of the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prio</em>' attribute.
   * @see #setPrio(int)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Prio()
   * @model
   * @generated
   */
  int getPrio();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.Task#getPrio <em>Prio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prio</em>' attribute.
   * @see #getPrio()
   * @generated
   */
  void setPrio(int value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(Duration)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Duration()
   * @model containment="true"
   * @generated
   */
  Duration getDuration();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.Task#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Duration value);

  /**
   * Returns the value of the '<em><b>Projects</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks.taskDSL.Project}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projects</em>' containment reference list.
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Projects()
   * @model containment="true"
   * @generated
   */
  EList<Project> getProjects();

  /**
   * Returns the value of the '<em><b>Use</b></em>' containment reference list.
   * The list contents are of type {@link persons.tasks.taskDSL.ProjectUse}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use</em>' containment reference list.
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Use()
   * @model containment="true"
   * @generated
   */
  EList<ProjectUse> getUse();

  /**
   * Returns the value of the '<em><b>Extends</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extends</em>' reference.
   * @see #setExtends(Task)
   * @see persons.tasks.taskDSL.TaskDSLPackage#getTask_Extends()
   * @model
   * @generated
   */
  Task getExtends();

  /**
   * Sets the value of the '{@link persons.tasks.taskDSL.Task#getExtends <em>Extends</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extends</em>' reference.
   * @see #getExtends()
   * @generated
   */
  void setExtends(Task value);

} // Task
