/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.taskDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see persons.tasks.taskDSL.TaskDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TaskDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "taskDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tasks.persons/TaskDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "taskDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TaskDSLPackage eINSTANCE = persons.tasks.taskDSL.impl.TaskDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PlanningImpl <em>Planning</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PlanningImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPlanning()
   * @generated
   */
  int PLANNING = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__NAME = 0;

  /**
   * The feature id for the '<em><b>Anonymous</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__ANONYMOUS = 1;

  /**
   * The feature id for the '<em><b>Persons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__PERSONS = 2;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING__TASKS = 3;

  /**
   * The number of structural features of the '<em>Planning</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLANNING_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PersonImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON__NAME = 0;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.TaskImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTION = 1;

  /**
   * The feature id for the '<em><b>Persons</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PERSONS = 2;

  /**
   * The feature id for the '<em><b>Prio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIO = 3;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DURATION = 4;

  /**
   * The feature id for the '<em><b>Projects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PROJECTS = 5;

  /**
   * The feature id for the '<em><b>Use</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__USE = 6;

  /**
   * The feature id for the '<em><b>Extends</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__EXTENDS = 7;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ProjectImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__NAME = 0;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ProjectUseImpl <em>Project Use</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ProjectUseImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getProjectUse()
   * @generated
   */
  int PROJECT_USE = 4;

  /**
   * The feature id for the '<em><b>Project</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_USE__PROJECT = 0;

  /**
   * The number of structural features of the '<em>Project Use</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_USE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.DurationImpl <em>Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.DurationImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getDuration()
   * @generated
   */
  int DURATION = 5;

  /**
   * The feature id for the '<em><b>Dl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__DL = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__UNIT = 1;

  /**
   * The number of structural features of the '<em>Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getAction()
   * @generated
   */
  int ACTION = 6;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.LunchActionImpl <em>Lunch Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.LunchActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getLunchAction()
   * @generated
   */
  int LUNCH_ACTION = 7;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION__LOCATION = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lunch Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUNCH_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.MeetingActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getMeetingAction()
   * @generated
   */
  int MEETING_ACTION = 8;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION__TOPIC = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Meeting Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEETING_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PaperActionImpl <em>Paper Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PaperActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaperAction()
   * @generated
   */
  int PAPER_ACTION = 9;

  /**
   * The feature id for the '<em><b>Report</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION__REPORT = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paper Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAPER_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.PaymentActionImpl <em>Payment Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.PaymentActionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaymentAction()
   * @generated
   */
  int PAYMENT_ACTION = 10;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION__CONDITION = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION__AMOUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Payment Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYMENT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.IntExpressionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 11;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionMinusImpl <em>Expression Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionMinusImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMinus()
   * @generated
   */
  int EXPRESSION_MINUS = 12;

  /**
   * The feature id for the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MINUS__SUB = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MINUS_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionPlusImpl <em>Expression Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionPlusImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionPlus()
   * @generated
   */
  int EXPRESSION_PLUS = 13;

  /**
   * The feature id for the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_PLUS__SUB = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_PLUS_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionBracketImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBracket()
   * @generated
   */
  int EXPRESSION_BRACKET = 14;

  /**
   * The feature id for the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET__SUB = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Bracket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionConstantIntImpl <em>Expression Constant Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionConstantIntImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionConstantInt()
   * @generated
   */
  int EXPRESSION_CONSTANT_INT = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_CONSTANT_INT__VALUE = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Constant Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_CONSTANT_INT_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionBalanceImpl <em>Expression Balance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionBalanceImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBalance()
   * @generated
   */
  int EXPRESSION_BALANCE = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BALANCE__VALUE = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Balance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BALANCE_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.BooleanExpressionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpression()
   * @generated
   */
  int BOOLEAN_EXPRESSION = 17;

  /**
   * The number of structural features of the '<em>Boolean Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.NotExpressionImpl <em>Not Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.NotExpressionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getNotExpression()
   * @generated
   */
  int NOT_EXPRESSION = 18;

  /**
   * The feature id for the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPRESSION__SUB = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPRESSION_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionBracketImpl <em>Boolean Expression Bracket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.BooleanExpressionBracketImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpressionBracket()
   * @generated
   */
  int BOOLEAN_EXPRESSION_BRACKET = 19;

  /**
   * The feature id for the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_BRACKET__SUB = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Expression Bracket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_BRACKET_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionConstantImpl <em>Boolean Expression Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.BooleanExpressionConstantImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpressionConstant()
   * @generated
   */
  int BOOLEAN_EXPRESSION_CONSTANT = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_CONSTANT__VALUE = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Expression Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_EXPRESSION_CONSTANT_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionAdditionImpl <em>Expression Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionAdditionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionAddition()
   * @generated
   */
  int EXPRESSION_ADDITION = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_ADDITION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_ADDITION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_ADDITION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionSubtractionImpl <em>Expression Subtraction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionSubtractionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionSubtraction()
   * @generated
   */
  int EXPRESSION_SUBTRACTION = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SUBTRACTION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SUBTRACTION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Subtraction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_SUBTRACTION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionMultiplyImpl <em>Expression Multiply</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionMultiplyImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMultiply()
   * @generated
   */
  int EXPRESSION_MULTIPLY = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MULTIPLY__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MULTIPLY__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Multiply</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MULTIPLY_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionDivisionImpl <em>Expression Division</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionDivisionImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionDivision()
   * @generated
   */
  int EXPRESSION_DIVISION = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_DIVISION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_DIVISION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Division</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_DIVISION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionMaximumImpl <em>Expression Maximum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionMaximumImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMaximum()
   * @generated
   */
  int EXPRESSION_MAXIMUM = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MAXIMUM__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MAXIMUM__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Maximum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MAXIMUM_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionMinimumImpl <em>Expression Minimum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionMinimumImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMinimum()
   * @generated
   */
  int EXPRESSION_MINIMUM = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MINIMUM__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MINIMUM__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Minimum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MINIMUM_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionModuloImpl <em>Expression Modulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionModuloImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionModulo()
   * @generated
   */
  int EXPRESSION_MODULO = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MODULO__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MODULO__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Modulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_MODULO_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionPowerImpl <em>Expression Power</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionPowerImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionPower()
   * @generated
   */
  int EXPRESSION_POWER = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_POWER__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_POWER__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Expression Power</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_POWER_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionBinOpImpl <em>Expression Bin Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionBinOpImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBinOp()
   * @generated
   */
  int EXPRESSION_BIN_OP = 29;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BIN_OP__LEFT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BIN_OP__BOP = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BIN_OP__RIGHT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Expression Bin Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BIN_OP_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.impl.ExpressionCompOpImpl <em>Expression Comp Op</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.impl.ExpressionCompOpImpl
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionCompOp()
   * @generated
   */
  int EXPRESSION_COMP_OP = 30;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_COMP_OP__LEFT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_COMP_OP__OP = BOOLEAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_COMP_OP__RIGHT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Expression Comp Op</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_COMP_OP_FEATURE_COUNT = BOOLEAN_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.TimeUnit
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 31;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.Balance <em>Balance</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.Balance
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBalance()
   * @generated
   */
  int BALANCE = 32;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.BinaryBooleanOperator <em>Binary Boolean Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.BinaryBooleanOperator
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBinaryBooleanOperator()
   * @generated
   */
  int BINARY_BOOLEAN_OPERATOR = 33;

  /**
   * The meta object id for the '{@link persons.tasks.taskDSL.CompareOperator <em>Compare Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see persons.tasks.taskDSL.CompareOperator
   * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getCompareOperator()
   * @generated
   */
  int COMPARE_OPERATOR = 34;


  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Planning <em>Planning</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Planning</em>'.
   * @see persons.tasks.taskDSL.Planning
   * @generated
   */
  EClass getPlanning();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Planning#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks.taskDSL.Planning#getName()
   * @see #getPlanning()
   * @generated
   */
  EAttribute getPlanning_Name();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Planning#isAnonymous <em>Anonymous</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Anonymous</em>'.
   * @see persons.tasks.taskDSL.Planning#isAnonymous()
   * @see #getPlanning()
   * @generated
   */
  EAttribute getPlanning_Anonymous();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.Planning#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Persons</em>'.
   * @see persons.tasks.taskDSL.Planning#getPersons()
   * @see #getPlanning()
   * @generated
   */
  EReference getPlanning_Persons();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.Planning#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see persons.tasks.taskDSL.Planning#getTasks()
   * @see #getPlanning()
   * @generated
   */
  EReference getPlanning_Tasks();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see persons.tasks.taskDSL.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Person#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks.taskDSL.Person#getName()
   * @see #getPerson()
   * @generated
   */
  EAttribute getPerson_Name();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see persons.tasks.taskDSL.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks.taskDSL.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.Task#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see persons.tasks.taskDSL.Task#getAction()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Action();

  /**
   * Returns the meta object for the reference list '{@link persons.tasks.taskDSL.Task#getPersons <em>Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Persons</em>'.
   * @see persons.tasks.taskDSL.Task#getPersons()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Persons();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Task#getPrio <em>Prio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prio</em>'.
   * @see persons.tasks.taskDSL.Task#getPrio()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Prio();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.Task#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see persons.tasks.taskDSL.Task#getDuration()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Duration();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.Task#getProjects <em>Projects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Projects</em>'.
   * @see persons.tasks.taskDSL.Task#getProjects()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Projects();

  /**
   * Returns the meta object for the containment reference list '{@link persons.tasks.taskDSL.Task#getUse <em>Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Use</em>'.
   * @see persons.tasks.taskDSL.Task#getUse()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Use();

  /**
   * Returns the meta object for the reference '{@link persons.tasks.taskDSL.Task#getExtends <em>Extends</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Extends</em>'.
   * @see persons.tasks.taskDSL.Task#getExtends()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Extends();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see persons.tasks.taskDSL.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Project#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see persons.tasks.taskDSL.Project#getName()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Name();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ProjectUse <em>Project Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project Use</em>'.
   * @see persons.tasks.taskDSL.ProjectUse
   * @generated
   */
  EClass getProjectUse();

  /**
   * Returns the meta object for the reference '{@link persons.tasks.taskDSL.ProjectUse#getProject <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Project</em>'.
   * @see persons.tasks.taskDSL.ProjectUse#getProject()
   * @see #getProjectUse()
   * @generated
   */
  EReference getProjectUse_Project();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Duration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Duration</em>'.
   * @see persons.tasks.taskDSL.Duration
   * @generated
   */
  EClass getDuration();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Duration#getDl <em>Dl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dl</em>'.
   * @see persons.tasks.taskDSL.Duration#getDl()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Dl();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.Duration#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see persons.tasks.taskDSL.Duration#getUnit()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Unit();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see persons.tasks.taskDSL.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.LunchAction <em>Lunch Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lunch Action</em>'.
   * @see persons.tasks.taskDSL.LunchAction
   * @generated
   */
  EClass getLunchAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.LunchAction#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see persons.tasks.taskDSL.LunchAction#getLocation()
   * @see #getLunchAction()
   * @generated
   */
  EAttribute getLunchAction_Location();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.MeetingAction <em>Meeting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meeting Action</em>'.
   * @see persons.tasks.taskDSL.MeetingAction
   * @generated
   */
  EClass getMeetingAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.MeetingAction#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see persons.tasks.taskDSL.MeetingAction#getTopic()
   * @see #getMeetingAction()
   * @generated
   */
  EAttribute getMeetingAction_Topic();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.PaperAction <em>Paper Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paper Action</em>'.
   * @see persons.tasks.taskDSL.PaperAction
   * @generated
   */
  EClass getPaperAction();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.PaperAction#getReport <em>Report</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Report</em>'.
   * @see persons.tasks.taskDSL.PaperAction#getReport()
   * @see #getPaperAction()
   * @generated
   */
  EAttribute getPaperAction_Report();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.PaymentAction <em>Payment Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payment Action</em>'.
   * @see persons.tasks.taskDSL.PaymentAction
   * @generated
   */
  EClass getPaymentAction();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.PaymentAction#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see persons.tasks.taskDSL.PaymentAction#getCondition()
   * @see #getPaymentAction()
   * @generated
   */
  EReference getPaymentAction_Condition();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.PaymentAction#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Amount</em>'.
   * @see persons.tasks.taskDSL.PaymentAction#getAmount()
   * @see #getPaymentAction()
   * @generated
   */
  EReference getPaymentAction_Amount();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see persons.tasks.taskDSL.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionMinus <em>Expression Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Minus</em>'.
   * @see persons.tasks.taskDSL.ExpressionMinus
   * @generated
   */
  EClass getExpressionMinus();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMinus#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub</em>'.
   * @see persons.tasks.taskDSL.ExpressionMinus#getSub()
   * @see #getExpressionMinus()
   * @generated
   */
  EReference getExpressionMinus_Sub();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionPlus <em>Expression Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Plus</em>'.
   * @see persons.tasks.taskDSL.ExpressionPlus
   * @generated
   */
  EClass getExpressionPlus();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionPlus#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub</em>'.
   * @see persons.tasks.taskDSL.ExpressionPlus#getSub()
   * @see #getExpressionPlus()
   * @generated
   */
  EReference getExpressionPlus_Sub();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionBracket <em>Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Bracket</em>'.
   * @see persons.tasks.taskDSL.ExpressionBracket
   * @generated
   */
  EClass getExpressionBracket();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionBracket#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub</em>'.
   * @see persons.tasks.taskDSL.ExpressionBracket#getSub()
   * @see #getExpressionBracket()
   * @generated
   */
  EReference getExpressionBracket_Sub();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionConstantInt <em>Expression Constant Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Constant Int</em>'.
   * @see persons.tasks.taskDSL.ExpressionConstantInt
   * @generated
   */
  EClass getExpressionConstantInt();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.ExpressionConstantInt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see persons.tasks.taskDSL.ExpressionConstantInt#getValue()
   * @see #getExpressionConstantInt()
   * @generated
   */
  EAttribute getExpressionConstantInt_Value();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionBalance <em>Expression Balance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Balance</em>'.
   * @see persons.tasks.taskDSL.ExpressionBalance
   * @generated
   */
  EClass getExpressionBalance();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.ExpressionBalance#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see persons.tasks.taskDSL.ExpressionBalance#getValue()
   * @see #getExpressionBalance()
   * @generated
   */
  EAttribute getExpressionBalance_Value();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression</em>'.
   * @see persons.tasks.taskDSL.BooleanExpression
   * @generated
   */
  EClass getBooleanExpression();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.NotExpression <em>Not Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Expression</em>'.
   * @see persons.tasks.taskDSL.NotExpression
   * @generated
   */
  EClass getNotExpression();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.NotExpression#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub</em>'.
   * @see persons.tasks.taskDSL.NotExpression#getSub()
   * @see #getNotExpression()
   * @generated
   */
  EReference getNotExpression_Sub();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.BooleanExpressionBracket <em>Boolean Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression Bracket</em>'.
   * @see persons.tasks.taskDSL.BooleanExpressionBracket
   * @generated
   */
  EClass getBooleanExpressionBracket();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.BooleanExpressionBracket#getSub <em>Sub</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sub</em>'.
   * @see persons.tasks.taskDSL.BooleanExpressionBracket#getSub()
   * @see #getBooleanExpressionBracket()
   * @generated
   */
  EReference getBooleanExpressionBracket_Sub();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.BooleanExpressionConstant <em>Boolean Expression Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Expression Constant</em>'.
   * @see persons.tasks.taskDSL.BooleanExpressionConstant
   * @generated
   */
  EClass getBooleanExpressionConstant();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.BooleanExpressionConstant#isValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see persons.tasks.taskDSL.BooleanExpressionConstant#isValue()
   * @see #getBooleanExpressionConstant()
   * @generated
   */
  EAttribute getBooleanExpressionConstant_Value();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionAddition <em>Expression Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Addition</em>'.
   * @see persons.tasks.taskDSL.ExpressionAddition
   * @generated
   */
  EClass getExpressionAddition();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionAddition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionAddition#getLeft()
   * @see #getExpressionAddition()
   * @generated
   */
  EReference getExpressionAddition_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionAddition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionAddition#getRight()
   * @see #getExpressionAddition()
   * @generated
   */
  EReference getExpressionAddition_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionSubtraction <em>Expression Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Subtraction</em>'.
   * @see persons.tasks.taskDSL.ExpressionSubtraction
   * @generated
   */
  EClass getExpressionSubtraction();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionSubtraction#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionSubtraction#getLeft()
   * @see #getExpressionSubtraction()
   * @generated
   */
  EReference getExpressionSubtraction_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionSubtraction#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionSubtraction#getRight()
   * @see #getExpressionSubtraction()
   * @generated
   */
  EReference getExpressionSubtraction_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionMultiply <em>Expression Multiply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Multiply</em>'.
   * @see persons.tasks.taskDSL.ExpressionMultiply
   * @generated
   */
  EClass getExpressionMultiply();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMultiply#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionMultiply#getLeft()
   * @see #getExpressionMultiply()
   * @generated
   */
  EReference getExpressionMultiply_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMultiply#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionMultiply#getRight()
   * @see #getExpressionMultiply()
   * @generated
   */
  EReference getExpressionMultiply_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionDivision <em>Expression Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Division</em>'.
   * @see persons.tasks.taskDSL.ExpressionDivision
   * @generated
   */
  EClass getExpressionDivision();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionDivision#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionDivision#getLeft()
   * @see #getExpressionDivision()
   * @generated
   */
  EReference getExpressionDivision_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionDivision#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionDivision#getRight()
   * @see #getExpressionDivision()
   * @generated
   */
  EReference getExpressionDivision_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionMaximum <em>Expression Maximum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Maximum</em>'.
   * @see persons.tasks.taskDSL.ExpressionMaximum
   * @generated
   */
  EClass getExpressionMaximum();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMaximum#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionMaximum#getLeft()
   * @see #getExpressionMaximum()
   * @generated
   */
  EReference getExpressionMaximum_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMaximum#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionMaximum#getRight()
   * @see #getExpressionMaximum()
   * @generated
   */
  EReference getExpressionMaximum_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionMinimum <em>Expression Minimum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Minimum</em>'.
   * @see persons.tasks.taskDSL.ExpressionMinimum
   * @generated
   */
  EClass getExpressionMinimum();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMinimum#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionMinimum#getLeft()
   * @see #getExpressionMinimum()
   * @generated
   */
  EReference getExpressionMinimum_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionMinimum#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionMinimum#getRight()
   * @see #getExpressionMinimum()
   * @generated
   */
  EReference getExpressionMinimum_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionModulo <em>Expression Modulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Modulo</em>'.
   * @see persons.tasks.taskDSL.ExpressionModulo
   * @generated
   */
  EClass getExpressionModulo();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionModulo#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionModulo#getLeft()
   * @see #getExpressionModulo()
   * @generated
   */
  EReference getExpressionModulo_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionModulo#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionModulo#getRight()
   * @see #getExpressionModulo()
   * @generated
   */
  EReference getExpressionModulo_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionPower <em>Expression Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Power</em>'.
   * @see persons.tasks.taskDSL.ExpressionPower
   * @generated
   */
  EClass getExpressionPower();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionPower#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionPower#getLeft()
   * @see #getExpressionPower()
   * @generated
   */
  EReference getExpressionPower_Left();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionPower#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionPower#getRight()
   * @see #getExpressionPower()
   * @generated
   */
  EReference getExpressionPower_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionBinOp <em>Expression Bin Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Bin Op</em>'.
   * @see persons.tasks.taskDSL.ExpressionBinOp
   * @generated
   */
  EClass getExpressionBinOp();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionBinOp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionBinOp#getLeft()
   * @see #getExpressionBinOp()
   * @generated
   */
  EReference getExpressionBinOp_Left();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.ExpressionBinOp#getBop <em>Bop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bop</em>'.
   * @see persons.tasks.taskDSL.ExpressionBinOp#getBop()
   * @see #getExpressionBinOp()
   * @generated
   */
  EAttribute getExpressionBinOp_Bop();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionBinOp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionBinOp#getRight()
   * @see #getExpressionBinOp()
   * @generated
   */
  EReference getExpressionBinOp_Right();

  /**
   * Returns the meta object for class '{@link persons.tasks.taskDSL.ExpressionCompOp <em>Expression Comp Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Comp Op</em>'.
   * @see persons.tasks.taskDSL.ExpressionCompOp
   * @generated
   */
  EClass getExpressionCompOp();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionCompOp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see persons.tasks.taskDSL.ExpressionCompOp#getLeft()
   * @see #getExpressionCompOp()
   * @generated
   */
  EReference getExpressionCompOp_Left();

  /**
   * Returns the meta object for the attribute '{@link persons.tasks.taskDSL.ExpressionCompOp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see persons.tasks.taskDSL.ExpressionCompOp#getOp()
   * @see #getExpressionCompOp()
   * @generated
   */
  EAttribute getExpressionCompOp_Op();

  /**
   * Returns the meta object for the containment reference '{@link persons.tasks.taskDSL.ExpressionCompOp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see persons.tasks.taskDSL.ExpressionCompOp#getRight()
   * @see #getExpressionCompOp()
   * @generated
   */
  EReference getExpressionCompOp_Right();

  /**
   * Returns the meta object for enum '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see persons.tasks.taskDSL.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the meta object for enum '{@link persons.tasks.taskDSL.Balance <em>Balance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Balance</em>'.
   * @see persons.tasks.taskDSL.Balance
   * @generated
   */
  EEnum getBalance();

  /**
   * Returns the meta object for enum '{@link persons.tasks.taskDSL.BinaryBooleanOperator <em>Binary Boolean Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Binary Boolean Operator</em>'.
   * @see persons.tasks.taskDSL.BinaryBooleanOperator
   * @generated
   */
  EEnum getBinaryBooleanOperator();

  /**
   * Returns the meta object for enum '{@link persons.tasks.taskDSL.CompareOperator <em>Compare Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Compare Operator</em>'.
   * @see persons.tasks.taskDSL.CompareOperator
   * @generated
   */
  EEnum getCompareOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TaskDSLFactory getTaskDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PlanningImpl <em>Planning</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PlanningImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPlanning()
     * @generated
     */
    EClass PLANNING = eINSTANCE.getPlanning();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLANNING__NAME = eINSTANCE.getPlanning_Name();

    /**
     * The meta object literal for the '<em><b>Anonymous</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLANNING__ANONYMOUS = eINSTANCE.getPlanning_Anonymous();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLANNING__PERSONS = eINSTANCE.getPlanning_Persons();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLANNING__TASKS = eINSTANCE.getPlanning_Tasks();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PersonImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON__NAME = eINSTANCE.getPerson_Name();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.TaskImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ACTION = eINSTANCE.getTask_Action();

    /**
     * The meta object literal for the '<em><b>Persons</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PERSONS = eINSTANCE.getTask_Persons();

    /**
     * The meta object literal for the '<em><b>Prio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__PRIO = eINSTANCE.getTask_Prio();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__DURATION = eINSTANCE.getTask_Duration();

    /**
     * The meta object literal for the '<em><b>Projects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PROJECTS = eINSTANCE.getTask_Projects();

    /**
     * The meta object literal for the '<em><b>Use</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__USE = eINSTANCE.getTask_Use();

    /**
     * The meta object literal for the '<em><b>Extends</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__EXTENDS = eINSTANCE.getTask_Extends();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ProjectImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__NAME = eINSTANCE.getProject_Name();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ProjectUseImpl <em>Project Use</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ProjectUseImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getProjectUse()
     * @generated
     */
    EClass PROJECT_USE = eINSTANCE.getProjectUse();

    /**
     * The meta object literal for the '<em><b>Project</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT_USE__PROJECT = eINSTANCE.getProjectUse_Project();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.DurationImpl <em>Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.DurationImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getDuration()
     * @generated
     */
    EClass DURATION = eINSTANCE.getDuration();

    /**
     * The meta object literal for the '<em><b>Dl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__DL = eINSTANCE.getDuration_Dl();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__UNIT = eINSTANCE.getDuration_Unit();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.LunchActionImpl <em>Lunch Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.LunchActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getLunchAction()
     * @generated
     */
    EClass LUNCH_ACTION = eINSTANCE.getLunchAction();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LUNCH_ACTION__LOCATION = eINSTANCE.getLunchAction_Location();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.MeetingActionImpl <em>Meeting Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.MeetingActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getMeetingAction()
     * @generated
     */
    EClass MEETING_ACTION = eINSTANCE.getMeetingAction();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEETING_ACTION__TOPIC = eINSTANCE.getMeetingAction_Topic();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PaperActionImpl <em>Paper Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PaperActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaperAction()
     * @generated
     */
    EClass PAPER_ACTION = eINSTANCE.getPaperAction();

    /**
     * The meta object literal for the '<em><b>Report</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAPER_ACTION__REPORT = eINSTANCE.getPaperAction_Report();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.PaymentActionImpl <em>Payment Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.PaymentActionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getPaymentAction()
     * @generated
     */
    EClass PAYMENT_ACTION = eINSTANCE.getPaymentAction();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAYMENT_ACTION__CONDITION = eINSTANCE.getPaymentAction_Condition();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAYMENT_ACTION__AMOUNT = eINSTANCE.getPaymentAction_Amount();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.IntExpressionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionMinusImpl <em>Expression Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionMinusImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMinus()
     * @generated
     */
    EClass EXPRESSION_MINUS = eINSTANCE.getExpressionMinus();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MINUS__SUB = eINSTANCE.getExpressionMinus_Sub();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionPlusImpl <em>Expression Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionPlusImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionPlus()
     * @generated
     */
    EClass EXPRESSION_PLUS = eINSTANCE.getExpressionPlus();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_PLUS__SUB = eINSTANCE.getExpressionPlus_Sub();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionBracketImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBracket()
     * @generated
     */
    EClass EXPRESSION_BRACKET = eINSTANCE.getExpressionBracket();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_BRACKET__SUB = eINSTANCE.getExpressionBracket_Sub();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionConstantIntImpl <em>Expression Constant Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionConstantIntImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionConstantInt()
     * @generated
     */
    EClass EXPRESSION_CONSTANT_INT = eINSTANCE.getExpressionConstantInt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_CONSTANT_INT__VALUE = eINSTANCE.getExpressionConstantInt_Value();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionBalanceImpl <em>Expression Balance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionBalanceImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBalance()
     * @generated
     */
    EClass EXPRESSION_BALANCE = eINSTANCE.getExpressionBalance();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_BALANCE__VALUE = eINSTANCE.getExpressionBalance_Value();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionImpl <em>Boolean Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.BooleanExpressionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpression()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION = eINSTANCE.getBooleanExpression();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.NotExpressionImpl <em>Not Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.NotExpressionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getNotExpression()
     * @generated
     */
    EClass NOT_EXPRESSION = eINSTANCE.getNotExpression();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EXPRESSION__SUB = eINSTANCE.getNotExpression_Sub();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionBracketImpl <em>Boolean Expression Bracket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.BooleanExpressionBracketImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpressionBracket()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION_BRACKET = eINSTANCE.getBooleanExpressionBracket();

    /**
     * The meta object literal for the '<em><b>Sub</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOLEAN_EXPRESSION_BRACKET__SUB = eINSTANCE.getBooleanExpressionBracket_Sub();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.BooleanExpressionConstantImpl <em>Boolean Expression Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.BooleanExpressionConstantImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBooleanExpressionConstant()
     * @generated
     */
    EClass BOOLEAN_EXPRESSION_CONSTANT = eINSTANCE.getBooleanExpressionConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_EXPRESSION_CONSTANT__VALUE = eINSTANCE.getBooleanExpressionConstant_Value();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionAdditionImpl <em>Expression Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionAdditionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionAddition()
     * @generated
     */
    EClass EXPRESSION_ADDITION = eINSTANCE.getExpressionAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_ADDITION__LEFT = eINSTANCE.getExpressionAddition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_ADDITION__RIGHT = eINSTANCE.getExpressionAddition_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionSubtractionImpl <em>Expression Subtraction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionSubtractionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionSubtraction()
     * @generated
     */
    EClass EXPRESSION_SUBTRACTION = eINSTANCE.getExpressionSubtraction();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_SUBTRACTION__LEFT = eINSTANCE.getExpressionSubtraction_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_SUBTRACTION__RIGHT = eINSTANCE.getExpressionSubtraction_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionMultiplyImpl <em>Expression Multiply</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionMultiplyImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMultiply()
     * @generated
     */
    EClass EXPRESSION_MULTIPLY = eINSTANCE.getExpressionMultiply();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MULTIPLY__LEFT = eINSTANCE.getExpressionMultiply_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MULTIPLY__RIGHT = eINSTANCE.getExpressionMultiply_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionDivisionImpl <em>Expression Division</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionDivisionImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionDivision()
     * @generated
     */
    EClass EXPRESSION_DIVISION = eINSTANCE.getExpressionDivision();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_DIVISION__LEFT = eINSTANCE.getExpressionDivision_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_DIVISION__RIGHT = eINSTANCE.getExpressionDivision_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionMaximumImpl <em>Expression Maximum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionMaximumImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMaximum()
     * @generated
     */
    EClass EXPRESSION_MAXIMUM = eINSTANCE.getExpressionMaximum();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MAXIMUM__LEFT = eINSTANCE.getExpressionMaximum_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MAXIMUM__RIGHT = eINSTANCE.getExpressionMaximum_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionMinimumImpl <em>Expression Minimum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionMinimumImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionMinimum()
     * @generated
     */
    EClass EXPRESSION_MINIMUM = eINSTANCE.getExpressionMinimum();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MINIMUM__LEFT = eINSTANCE.getExpressionMinimum_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MINIMUM__RIGHT = eINSTANCE.getExpressionMinimum_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionModuloImpl <em>Expression Modulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionModuloImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionModulo()
     * @generated
     */
    EClass EXPRESSION_MODULO = eINSTANCE.getExpressionModulo();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MODULO__LEFT = eINSTANCE.getExpressionModulo_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_MODULO__RIGHT = eINSTANCE.getExpressionModulo_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionPowerImpl <em>Expression Power</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionPowerImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionPower()
     * @generated
     */
    EClass EXPRESSION_POWER = eINSTANCE.getExpressionPower();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_POWER__LEFT = eINSTANCE.getExpressionPower_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_POWER__RIGHT = eINSTANCE.getExpressionPower_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionBinOpImpl <em>Expression Bin Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionBinOpImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionBinOp()
     * @generated
     */
    EClass EXPRESSION_BIN_OP = eINSTANCE.getExpressionBinOp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_BIN_OP__LEFT = eINSTANCE.getExpressionBinOp_Left();

    /**
     * The meta object literal for the '<em><b>Bop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_BIN_OP__BOP = eINSTANCE.getExpressionBinOp_Bop();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_BIN_OP__RIGHT = eINSTANCE.getExpressionBinOp_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.impl.ExpressionCompOpImpl <em>Expression Comp Op</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.impl.ExpressionCompOpImpl
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getExpressionCompOp()
     * @generated
     */
    EClass EXPRESSION_COMP_OP = eINSTANCE.getExpressionCompOp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_COMP_OP__LEFT = eINSTANCE.getExpressionCompOp_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION_COMP_OP__OP = eINSTANCE.getExpressionCompOp_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_COMP_OP__RIGHT = eINSTANCE.getExpressionCompOp_Right();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.TimeUnit
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.Balance <em>Balance</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.Balance
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBalance()
     * @generated
     */
    EEnum BALANCE = eINSTANCE.getBalance();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.BinaryBooleanOperator <em>Binary Boolean Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.BinaryBooleanOperator
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getBinaryBooleanOperator()
     * @generated
     */
    EEnum BINARY_BOOLEAN_OPERATOR = eINSTANCE.getBinaryBooleanOperator();

    /**
     * The meta object literal for the '{@link persons.tasks.taskDSL.CompareOperator <em>Compare Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see persons.tasks.taskDSL.CompareOperator
     * @see persons.tasks.taskDSL.impl.TaskDSLPackageImpl#getCompareOperator()
     * @generated
     */
    EEnum COMPARE_OPERATOR = eINSTANCE.getCompareOperator();

  }

} //TaskDSLPackage
