/*
 * generated by Xtext 2.32.0
 */
package persons.tasks.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTaskDSLScopeProvider extends DelegatingScopeProvider {
}
