/*
 * generated by Xtext 2.32.0
 */
package persons.tasks.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import persons.tasks.TaskDSLRuntimeModule
import persons.tasks.TaskDSLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TaskDSLRuntimeModule, new TaskDSLIdeModule))
	}
	
}
